name: Workflow1
on:
    push:
        branches:
          - 'v[1-9].[1-9]'

jobs:
    my_first_job:
        runs-on: ubuntu-latest

        steps:
          - name: Check Commit Message
            id: check_commit
            run: |
              for commit in $(git log --format=%B -n 1 ${{ github.sha }}); do
              if [[ $commit == '#NORUN'* ]]; then
                echo "Commit message starts with #NORUN, hence pipeline will not run."
                exit 78  # Exit with a neutral status (success but with a message).
              fi
              done
            shell: bash
          
          - name: checkout my source
            id: check_out_my_source
            uses: actions/checkout@v4

          - name: Slack Notification
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
          - name: Run Trivy vulnerability scanner
            uses: aquasecurity/trivy-action@master
            with:
              scan-ref: 'fs'
              scan-type: 'fs'
              format: 'table'
              exit-code: '1'
              ignore-unfixed: true
              vuln-type: 'os,library'
              severity: 'CRITICAL,HIGH'
              

          - uses: MeilCli/slack-upload-file@v3
            with:
              slack_token: ${{ secrets.SLACK_TOKEN }}
              channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
              content: 'file content'
              file_type: 'text'
              file_name: 'text.txt'
              title: 'title of file'
              initial_comment: 'post by slack-upload-file'

          
            


           


