name: Workflow1
on:
    push:
        branches:
            - v\d+\.\d+
            ##\d+ matches one or more digit
            ##\. matches literal dot

jobs:
    my_first_job:
        runs-on: ubuntu-latest

        steps:
            - name: Slack Message
              id: slack_message
              uses: rtCamp/action-slack-notify@v2
              with:
                payload: |
                  {
                  "type": "section",  
                  "text": {
                      "type": "mrkdwn"
                      "text": "*Name*: testName"
                      "text": "*Matriculation*: testMatri"
                      "text": "*Email*: testEmail"
                      "text": "*Git*: testGitLink"
                      "text": "*Image*: testImageLink"
                    }
                  }        
              env:
                SLACK_TITLE: Post Title
                SLACK_WEBHOOK_URL: ${{secrets.SLACK_TEST_SUBMISSION}}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

            - name: checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                repository: origin/checkout

           


